--- Makefile	2007-05-29 16:13:41.000000000 +0300
+++ Makefile.fixed	2007-07-30 18:57:18.000000000 +0300
@@ -29,19 +29,23 @@
 	touch .bindir
 
 man/%.1: %.sgml .mandir
-	docbook-to-man $< > $@
+	docbook2man $<
+	mv IMDB-TOOLS.1 $@
 %.1: %.sgml .mandir
-	docbook-to-man $< > $@
+	docbook2man $<
+	mv IMDB-TOOLS.5 $@
 man/%.5: %.sgml .mandir
-	docbook-to-man $< > $@
+	docbook2man $<
+	mv IMDB-TOOLS.5 $@
 %.5: %.sgml .mandir
-	docbook-to-man $< > $@
+	docbook2man $<
+	mv IMDB-TOOLS.5 $@
 
 bin/%: %.sh .bindir
 	sed "s,%PREFIX%,$(PREFIX),;s,%VERSION%,$(VERSION),"  < $< > $@
 	chmod +x $@
 
-install: install-bin install-man install-doc
+install: install-bin install-man
 	
 install-bin: bin/imdb-get bin/imdb-rename bin/imdb-link bin/imdb-update-cache bin/imdb bin/imdb-fxd
 	install -d $(DESTDIR)$(BINPREFIX)
