--- Makefile.old	2006-11-25 16:06:58.000000000 +0200
+++ Makefile	2007-01-15 20:13:31.000000000 +0200
@@ -29,16 +29,18 @@
 	touch .bindir
 
 man/%.1: %.sgml .mandir
-	docbook-to-man $< > $@
+	docbook2man $<
+	mv IMDB-TOOLS.1 $@
 
 man/%.5: %.sgml .mandir
-	docbook-to-man $< > $@
+	docbook2man $<
+	mv IMDB-TOOLS.5 $@
 
 bin/%: %.sh .bindir
 	sed "s,%PREFIX%,$(PREFIX),"  < $< > $@
 	chmod +x $@
 
-install: install-bin install-man install-doc
+install: install-bin install-man
 	
 install-bin: bin/imdb-get bin/imdb-rename bin/imdb-link bin/imdb-update-cache bin/imdb
 	install -d $(DESTDIR)$(BINPREFIX)
